presentation/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using presentation.Services.IServices;
using System.Security.Claims;
using Utility;
using presentation.Models.Dto;
using System.IdentityModel.Tokens.Jwt;
using presentation.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace presentation.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        private readonly ITokenProvider _tokenProvider;
        public AuthController(IAuthService authService, ITokenProvider tokenProvider)
        {
            _authService = authService;
            _tokenProvider = tokenProvider;
        }

        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDTO obj = new();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequestDTO obj)
        {
            APIResponse response = await _authService.LoginAsync<APIResponse>(obj);
            if (response != null && response.IsSuccess)
            {
                TokenDTO model = JsonConvert.DeserializeObject<TokenDTO>(Convert.ToString(response.Result));

                var handler = new JwtSecurityTokenHandler();
                var jwt = handler.ReadJwtToken(model.AccessToken);

                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(u => u.Type == "unique_name").Value));

                identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);


                _tokenProvider.SetToken(model);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("CustomError", response.ErrorMessages.FirstOrDefault());
                return View(obj);
            }
        }

        [HttpGet]
        public IActionResult Register()
        {
            var roleList = new List<SelectListItem>()
            {
                  new SelectListItem{Text=SD.Admin,Value=SD.Admin},
                new SelectListItem{Text=SD.Customer,Value=SD.Customer},
            };
            ViewBag.RoleList = roleList;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterationRequestDTO obj)
        {
            if (string.IsNullOrEmpty(obj.Role))
            {
                obj.Role = SD.Customer;
            }
            APIResponse result = await _authService.RegisterAsync<APIResponse>(obj);
            if (result != null && result.IsSuccess)
            {
                return RedirectToAction("Login");
            }
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=SD.Admin,Value=SD.Admin},
                new SelectListItem{Text=SD.Customer,Value=SD.Customer},
            };
            ViewBag.RoleList = roleList;
            return View();
        }


        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            var token = _tokenProvider.GetToken();
            await _authService.LogoutAsync<APIResponse>(token);
            _tokenProvider.ClearToken();
            return RedirectToAction("Index", "Home");
        }


        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

presentation/Controllers/ResortController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using presentation.Models;
using presentation.Models.Dto;
using presentation.Services;
using presentation.Services.IServices;
using Utility;

namespace presentation.Controllers
{
    public class ResortController : Controller
    {
        private readonly IResortService _ResortService;
        private readonly IMapper _mapper;
        public ResortController(IResortService ResortService, IMapper mapper)
        {
            _ResortService = ResortService;
            _mapper = mapper;
        }

        public async Task<IActionResult> IndexResort()
        {
            List<ResortDTO> list = new();

            var response = await _ResortService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<ResortDTO>>(Convert.ToString(response.Result));
            }
            return View(list);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateResort()
        {
            return View();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateResort(ResortCreateDTO model)
        {
            if (ModelState.IsValid)
            {

                var response = await _ResortService.CreateAsync<APIResponse>(model) ;
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Resort created successfully";
                    return RedirectToAction(nameof(IndexResort));
                }
            }
            TempData["error"] = "Error encountered.";
            return View(model);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateResort(int ResortId)
        {
            var response = await _ResortService.GetAsync<APIResponse>(ResortId) ;
            if (response != null && response.IsSuccess)
            {

                ResortDTO model = JsonConvert.DeserializeObject<ResortDTO>(Convert.ToString(response.Result));
                return View(_mapper.Map<ResortUpdateDTO>(model));
            }
            return NotFound();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateResort(ResortUpdateDTO model)
        {
            if (ModelState.IsValid)
            {
                TempData["success"] = "Resort updated successfully";
                var response = await _ResortService.UpdateAsync<APIResponse>(model) ;
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexResort));
                }
            }
            TempData["error"] = "Error encountered.";
            return View(model);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteResort(int ResortId)
        {
            var response = await _ResortService.GetAsync<APIResponse>(ResortId) ;
            if (response != null && response.IsSuccess)
            {
                ResortDTO model = JsonConvert.DeserializeObject<ResortDTO>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteResort(ResortDTO model)
        {

            var response = await _ResortService.DeleteAsync<APIResponse>(model.Id);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Resort deleted successfully";
                return RedirectToAction(nameof(IndexResort));
            }
            TempData["error"] = "Error encountered.";
            return View(model);
        }

    }
}

presentation/Controllers/ResortNumberController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using presentation.Models;
using presentation.Models.Dto;
using presentation.Models.VM;
using presentation.Services;
using presentation.Services.IServices;
using Utility;

namespace presentation.Controllers
{
    public class ResortNumberController : Controller
    {
        private readonly IResortNumberService _ResortNumberService;
        private readonly IResortService _ResortService;
        private readonly IMapper _mapper;
        public ResortNumberController(IResortNumberService ResortNumberService, IMapper mapper, IResortService ResortService)
        {
            _ResortNumberService = ResortNumberService;
            _mapper = mapper;
            _ResortService = ResortService;
        }

        public async Task<IActionResult> IndexResortNumber()
        {
            List<ResortNumberDTO> list = new();

            var response = await _ResortNumberService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<ResortNumberDTO>>(Convert.ToString(response.Result));
            }
            return View(list);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateResortNumber()
        {
            ResortNumberCreateVM ResortNumberVM = new();
            var response = await _ResortService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                ResortNumberVM.ResortsList = JsonConvert.DeserializeObject<List<ResortDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    }); ;
            }
            return View(ResortNumberVM);
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateResortNumber(ResortNumberCreateVM model)
        {
            if (ModelState.IsValid)
            {

                var response = await _ResortNumberService.CreateAsync<APIResponse>(model.ResortNumber) ;
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexResortNumber));
                }
                else
                {
                    TempData["error"] = (response.ErrorMessages != null && response.ErrorMessages.Count > 0) ?
                        response.ErrorMessages[0] : "Error Encountered";
                }
            }

            var resp = await _ResortService.GetAllAsync<APIResponse>();
            if (resp != null && resp.IsSuccess)
            {
                model.ResortsList = JsonConvert.DeserializeObject<List<ResortDTO>>
                    (Convert.ToString(resp.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    }); ;
            }
            return View(model);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateResortNumber(int ResortNo)
        {
            ResortNumberUpdateVM ResortNumberVM = new();
            var response = await _ResortNumberService.GetAsync<APIResponse>(ResortNo) ;
            if (response != null && response.IsSuccess)
            {
                ResortNumberDTO model = JsonConvert.DeserializeObject<ResortNumberDTO>(Convert.ToString(response.Result));
                ResortNumberVM.ResortNumber = _mapper.Map<ResortNumberUpdateDTO>(model);
            }

            response = await _ResortService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                ResortNumberVM.ResortsList = JsonConvert.DeserializeObject<List<ResortDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
                return View(ResortNumberVM);
            }
            else
            {
                TempData["error"] = (response.ErrorMessages != null && response.ErrorMessages.Count > 0) ?
                    response.ErrorMessages[0] : "Error Encountered";
            }


            return NotFound();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateResortNumber(ResortNumberUpdateVM model)
        {
            if (ModelState.IsValid)
            {

                var response = await _ResortNumberService.UpdateAsync<APIResponse>(model.ResortNumber) ;
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexResortNumber));
                }
                else
                {
                    TempData["error"] = (response.ErrorMessages != null && response.ErrorMessages.Count > 0) ?
                        response.ErrorMessages[0] : "Error Encountered";
                }
            }

            var resp = await _ResortService.GetAllAsync<APIResponse>();
            if (resp != null && resp.IsSuccess)
            {
                model.ResortsList = JsonConvert.DeserializeObject<List<ResortDTO>>
                    (Convert.ToString(resp.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    }); ;
            }
            return View(model);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteResortNumber(int ResortNo)
        {
            ResortNumberDeleteVM ResortNumberVM = new();
            var response = await _ResortNumberService.GetAsync<APIResponse>(ResortNo) ;
            if (response != null && response.IsSuccess)
            {
                ResortNumberDTO model = JsonConvert.DeserializeObject<ResortNumberDTO>(Convert.ToString(response.Result));
                ResortNumberVM.ResortNumber = model;
            }

            response = await _ResortService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                ResortNumberVM.ResortsList = JsonConvert.DeserializeObject<List<ResortDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
                return View(ResortNumberVM);
            }


            return NotFound();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVillaNumber(ResortNumberDeleteVM model)
        {

            var response = await _ResortNumberService.DeleteAsync<APIResponse>(model.ResortNumber.ResortNo) ;
            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(IndexResortNumber));
            }
            else
            {
                TempData["error"] = (response.ErrorMessages != null && response.ErrorMessages.Count > 0) ?
                    response.ErrorMessages[0] : "Error Encountered";
            }

            return View(model);
        }



    }
}

presentation/Views/Shared/_Layout.cshtml
@using Utility
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - presentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/presentation.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body style="background-color: #12161d;">
    <partial name="_Notification" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light mybtn-success   box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://cdn-icons-png.flaticon.com/512/2627/2627036.png" style="width:35px" /></a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between text-white">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(SD.Admin))
                       {
                        <li class="nav-item dropdown text-white">
                            <a class=" nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" >
                                
                                    <span class="text-white">Content (Admin) </span>
                               
                                
                            </a>

                            <ul class="dropdown-menu text-white">

                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Resort" asp-action="IndexResort">
                                        Resort
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="ResortNumber" asp-action="IndexResortNumber">
                                        Resort Number
                                    </a>
                                </li>

                            </ul>

                        </li>
                        }
                    </ul>

                    <ul class="navbar-nav" >
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" href="#">Hello, @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - presentation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

presentation/Views/Shared/_Notification.cshtml
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@if (TempData["success"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '@TempData["success"]',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        })
        </script>
}
@if (TempData["error"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        })
    </script>
}